name: 🐞 Bug Report
description: Report a bug found on the site or in the private area
labels: [bug]
body:
  - type: input
    id: url
    attributes:
      label: Affected page or component
      placeholder: e.g. https://vivabite.life/crowdsale
    validations:
      required: false
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      placeholder: I clicked on "Save", but the changes didn’t persist
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: I expected the menu to be updated and confirmation to show
    validations:
      required: false
  - type: dropdown
    id: device
    attributes:
      label: Where did you encounter this issue?
      options:
        - Desktop (Chrome)
        - Desktop (Firefox)
        - Desktop (Edge)
        - Desktop (Safari)
        - Desktop (Other)
        - Mobile (iOS)
        - Mobile (Android)
        - Tablet
        - Other
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Screenshots or error messages
      description: Paste any relevant logs, errors or screenshots
